In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
A = np.array([[np.nan, np.nan, 2], [4, np.nan, 1], [10, 5, 9]])
print(A)

[[nan nan  2.]
 [ 4. nan  1.]
 [10.  5.  9.]]


In [4]:
#Compute the mean of each column, ignoring NaN values
np.nanmean(A, axis=0)

array([7., 5., 4.])

In [5]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

A_transformed = imp_mean.fit_transform(A)
A_transformed

array([[ 7.,  5.,  2.],
       [ 4.,  5.,  1.],
       [10.,  5.,  9.]])

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
# Create a polynomial feature transformer with degree 2
poly = PolynomialFeatures(2)
poly.fit_transform(A_transformed)





array([[  1.,   7.,   5.,   2.,  49.,  35.,  14.,  25.,  10.,   4.],
       [  1.,   4.,   5.,   1.,  16.,  20.,   4.,  25.,   5.,   1.],
       [  1.,  10.,   5.,   9., 100.,  50.,  90.,  25.,  45.,  81.]])

In [8]:
#Doing the steps above in a pipeline
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
    ('poly', PolynomialFeatures(2))
])

C = pipeline.fit_transform(A)
C

array([[  1.,   7.,   5.,   2.,  49.,  35.,  14.,  25.,  10.,   4.],
       [  1.,   4.,   5.,   1.,  16.,  20.,   4.,  25.,   5.,   1.],
       [  1.,  10.,   5.,   9., 100.,  50.,  90.,  25.,  45.,  81.]])