# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [67]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)
print(type(A))


2
(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(f"Print B:\n{B}")
print(f"Print C:\n{C}")
print(f"Elementwise subtraction:\n{B-C}")
print(f"Elementwise multiplication:\n{B*C}")
print(f"Matrix multiplication:\n{B@C}")


Print B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Print C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [27]:
D = np.arange(1, 10).reshape(3, 3)
print(D)
print(f"Exponentiate each number elementwise:\n{np.exp(D)}")
print(f"Calc min value in the matrix:\n{np.min(D)}")
print(f"Calc min value in each row:\n{np.min(D, axis=1)}")
print(f"Calc min value in each column:\n{np.min(D, axis=0)}")
print(f"Find index value for the min value in the matrix:\n{np.argmin(D)}")
print(f"Find index value for the min value in each row:\n{np.argmin(D, axis=1)}")
print(f"Calc sum for all elements:\n{np.sum(D)}")
print(f"Calc mean for each column:\n{np.mean(D, axis=0)}")
print(f"Calc median for each column:\n{np.median(D, axis=0)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Exponentiate each number elementwise:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Calc min value in the matrix:
1
Calc min value in each row:
[1 4 7]
Calc min value in each column:
[1 2 3]
Find index value for the min value in the matrix:
0
Find index value for the min value in each row:
[0 0 0]
Calc sum for all elements:
45
Calc mean for each column:
[4. 5. 6.]
Calc median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [28]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
#A[1]
A[1:2]

array([[ 6,  7,  8,  9, 10]])

**Answer:**

In [ ]:
# The answer to the question what it means 
# if you provide fewer indices than axes when slicing is that you
# only get a subset of the axes back. In the first example A[1] you
# will get back the second axes. It is actually implicit slicing 
# it is assumed that you want to 1 axes back. You get the same 
# row back if you explicitly slice A[1:2]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [36]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
A[0][0] = 10 #Just double checking so that we get the values and not the index
# Flatten the multidemension array in order to visit all elements
for i in A.flat:
    print(f"Number:{i}")

Number:10
Number:2
Number:3
Number:4
Number:5
Number:6
Number:7
Number:8
Number:9
Number:10
Number:11
Number:12
Number:13
Number:14
Number:15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [8]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#Answer: We start with a 1D array and reshape it int a 3D Array. 
# In this example we specify that we want 2 outer arrays with 3 arrays in each. 
# The last input value -1 tells NumPy that it can figure out the last dimension by 
# its self. In this instance we have 30 values which should be evenly distributed
# So, 2 x 3 = 6. Since 2 x 3 x 5 = 30 the last input value represents no. of
# columns in each array.

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [24]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [9]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [97]:
def add_mult_matrices(m1, m2, operation):
    #Check that m1 and m2 have the correct type, otherwise throw exception or print error message
    if not isinstance(m1, np.ndarray):
        raise TypeError("m1 is not of type numpy.ndarray")
    elif not isinstance(m2, np.ndarray):
        raise TypeError("m2 is not of type numpy.ndarray")
        
    
    #Check m1 and m2 so they are compatible to addition and multiplication
    try:
        np.broadcast_shapes(m1.shape, m2.shape)
    except Exception:
        raise ValueError(f"The matrices are not compatible with {operation} operation")
    
    #Check so that operation is either 'add' or 'multiply'
    if operation == 'add':
        return m1 + m2
    elif operation == 'multiply':
        return m1 @ m2
    else:
        raise ValueError("Operation provided is not supported")
    

arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr2 = np.array([1, 2, 4, 8, 16])
print(f"Add = {add_mult_matrices(arr1, arr2, 'add')}")
print(f"Multiply = {add_mult_matrices(arr1, arr2, 'multiply')}")


Add = [[ 2  4  7 12 21]
 [ 2  4  7 12 21]]
Multiply = [129 129]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [100]:
#Uppgift 10.1.1
#Definiera vektor x = (4, 3)
#a) Vilken dimension har vektorn x?
x = np.array([4, 3]).reshape(1, 2) #Ändra formen på listan så att vi kan räkna ut dimensionen
print("a) Vilken dimension har vektorn x?")
print(f"Svar: x har dimensionen 1 x 2 dvs 1 rad med 2 kolumner {x.shape}")

#b) Beräkna 5x
print("b) Beräkna 5x")
print(f"Svar: {5 * x}")

#c) Beräkna 3x
print("c) Beräkna 3x")
print(f"Svar: {3 * x}")

#d) Beräkna 5x + 3x
print("d) Beräkna 5x + 3x")
print(f"Svar: {5 * x + 3 * x}")

#e) Beräkna 8x
print("e) Beräkna 8x")
print(f"Svar: {8 * x}")

#f) Beräkna 4x - x
print("f) Beräkna 4x - x")
print(f"Svar: {4 * x - x}, detta eftersom 4x = 4x(4,3)=(4x4,4x3)=(16,12). Sedan minskar vi 4x med x dvs. (16,12)-(4,3)=(12,9)")

#g) Beräkna xT. Vilken blir den nya dimensionen efter transponeringen utförts?
print("g) Beräkna xT (transponatet). Dvs omvandla radvaktor till kolumnvektor")
print(f"Svar: Den nya dimensionen efter att transponeringen utförts blir {x.T.shape}")

#h) Är x + xT definierat?
print("h) Är x + xT definierat?")
print(f"Vi testar och ser om x + xT är definierat {add_mult_matrices(x, x.T, 'add')}")
print("Svar: Ja x + xT är definierat eftersom de har samma dimensioner.")

#i) Beräkna normen av x
print("i) Beräkna normen av x")
print(f"Svar: Normen av x = {np.linalg.norm(x, ord=2)}. Detta eftersom roten ur 4^2 + 3^2 = 5")


#Uppgift 10.1.2
#Definiera vektor v som v = (3, 7, 0, 11)
print("Uppgift 10.1.2")
print("Definiera vector v = (3,7,0,11)")
v = np.array([3,7,0,11]).reshape(4,1)
print(v)

#a) Vilken dimension har vektor v?
print("a) Vilken dimension har vektor v?")
print(f"Svar: Vektor v har dimensionen 4 rader med en 1 kolumn {v.shape}")

#b)Beräkna 2v
print("b) Beräkna 2v")
print(f"Svar: 2v =\n{2 * v}")

#c) Beräkna 5v + 2v
print("c) Beräkna 5v + 2v")
print(f"Svar: 5v + 2v =\n{add_mult_matrices((5 * v), (2 * v), 'add')}")

#d) Beräkna 4v - 2v
print("d) Beräkna 4v - 2v")
print(f"Svar: 4v - 2v = {(4 * v) - (2 * v)}")

#e) Beräkna vT, vilken blir den nya dimensionen efter transponeringen utförts?
print("e) Beräkna vT (transponatet). Dvs omvandla kolumnvektor till radvektor")
print(f"Dimensionen före transponering = {v.shape}")
print(f"Svar: Den nya dimensionen efter att transponeringen utförts blir {v.reshape(1,4).shape}")

#f) Beräkna normen av v
print("f) Beräkna normen av v med norm-funktionen i Numpy med enbart 1 argument, L2 antas som default av funktionen")
print(f"Svar: Normen av v = {np.linalg.norm(v)}. Detta eftersom roten ur 3^2 + 7^2 + 0^2 + 11^2 = ~13.38")

#Uppgift 10.1.3
print("Uppgift 10.1.3")
print("Definiera vectorerna v_1 och v_2")
v_1 = np.array([4,3,1,5])
v_2 = np.array([2,3,1,1])

#a) Beräkna normen v_1
print("a) Beräkna normen av v_1")
print(f"Svar: Normen av v_1 = {np.linalg.norm(v_1)}. Detta eftersom roten ur 4^2 + 3^2 + 1^2 + 5^2 = ~7.14")

#b) Beräkna normen av v_1 - v_2
print("b) Beräkna normen av v_1 - v2")
print(f"Svar: Normen av v_1 - v_2 = {np.linalg.norm(v_1 - v_2)}. Detta eftersom... ")


a) Vilken dimension har vektorn x?
Svar: x har dimensionen 1 x 2 dvs 1 rad med 2 kolumner (1, 2)
b) Beräkna 5x
Svar: [[20 15]]
c) Beräkna 3x
Svar: [[12  9]]
d) Beräkna 5x + 3x
Svar: [[32 24]]
e) Beräkna 8x
Svar: [[32 24]]
f) Beräkna 4x - x
Svar: [[12  9]], detta eftersom 4x = 4x(4,3)=(4x4,4x3)=(16,12). Sedan minskar vi 4x med x dvs. (16,12)-(4,3)=(12,9)
g) Beräkna xT (transponatet). Dvs omvandla radvaktor till kolumnvektor
Svar: Den nya dimensionen efter att transponeringen utförts blir (2, 1)
h) Är x + xT definierat?
Vi testar och ser om x + xT är definierat [[8 7]
 [7 6]]
Svar: Ja x + xT är definierat eftersom de har samma dimensioner.
i) Beräkna normen av x
Svar: Normen av x = 5.0. Detta eftersom roten ur 4^2 + 3^2 = 5
Uppgift 10.1.2
Definiera vector v = (3,7,0,11)
[[ 3]
 [ 7]
 [ 0]
 [11]]
a) Vilken dimension har vektor v?
Svar: Vektor v har dimensionen 4 rader med en 1 kolumn (4, 1)
b) Beräkna 2v
Svar: 2v =
[[ 6]
 [14]
 [ 0]
 [22]]
c) Beräkna 5v + 2v
Svar: 5v + 2v =
[[21]
 [49]
 [ 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [101]:
#Uppgift 10.2 Definiera matriserna
print("Uppgift 10.2 Definiera matriserna A-I")
A = np.array([[2, 1, -1], 
              [1, -1, 1]])
B = np.array([[4, -2, 1], 
              [2, -4, -2]])
C = np.array([[1, 2], 
              [2, 1]])
D = np.array([[3, 4], 
              [4, 3]])
E = np.array([[1], 
              [2]])
I = np.array([[1, 0], 
              [0, 1]])

#print("Test av transponat vs reshape:\n")
#print(f"B = {B}")
#print(f"Reshape B = {B.reshape(3,2)}")
#print(f"Transponat av B = {B.T}")

#Slutsats: Vi kan se att T ger ett riktigt transponat medans reshape enbart ger oss en viss form.

print("Om definierat, utför beräkningarna")
print("a) 2A")
print(f"Svar: 2A = {2 * A}")

print("b) B - 2A")
print(f"Svar: B - 2A = {B - (2 * A)}")

print("c) 3C - 2E är ej definierad eftersom matris C (2x2) och E(2x1) inte har samma dimensioner")

print("d) 2D - 3C")
print(f"Svar: 2D - 3C = {(2 * D) - (3 * C)}")

print("e) DT(transponat av D) + 2D")
print(f"Svar: DT + 2D {D.T + (2 * D)}")

print("f) 2CT - 2DT")
print(f"Svar: {(2 * C).T - (2 * D).T}")

print("g) AT - B")
print(f"Svar: AT - B är ej definierad eftersom A efter transponering får 2 kolumner med 3 rader medan B har 3 kolumner med 2 rader")

print("h) AC")
print("Svar: AC ej definierad eftersom A och C  har olika dimensioner")

print("i) CD")
print(f"Svar: CD = {add_mult_matrices(C, D, 'multiply')}")

print("j) CB")
print("Svar: CB ej definierad C och B  har olika dimensioner")

print("k) CI")
print(f"Svar: CI = {add_mult_matrices(C, I, 'multiply')}")

print("l) ABT")
print(f"Svar: ABT ej definierad eftersom transponatet av B får en annan dimension än A")

print("Uppgift 10.2.2")
print("Definiera matrisen A (på nytt, vi skriver över tidigare A)")
A = np.array([[2,3,4], 
              [5,4,1]])

print("Beräkna AAT")
print(f"Svar: AAT är ej definierad eftersom transponatet av får en annan dimension än A")

print("Uppgift 10.2.3")
print("Definiera matriserna A-C")
A = np.array([[1,2], 
              [2,4]])
B = np.array([[2,1], 
              [1,3]])
C = np.array([[4,3], 
              [0,2]])

print("Verifiera att AB = AC men att B inte är lika med C")
AB = A @ B #add_mult_matrices(A, B, 'multiply')
print(f"AB = \n{AB}")
AC = A @ C #add_mult_matrices(A, C, 'multiply')
print(f"AC = \n{AC}")
print(f"Är AB = AC? {np.array_equal(AB, AC)}") #Sant ifall båda matriserna har samma dimensioner och värden

print("Verifier att B inte är lika med C")
print(f"Är B = C? {np.array_equal(B, C)}") #Falskt ifall båda matriserna inte har samma dimensioner eller värden







Uppgift 10.2 Definiera matriserna A-I
Om definierat, utför beräkningarna
a) 2A
Svar: 2A = [[ 4  2 -2]
 [ 2 -2  2]]
b) B - 2A
Svar: B - 2A = [[ 0 -4  3]
 [ 0 -2 -4]]
c) 3C - 2E är ej definierad eftersom matris C (2x2) och E(2x1) inte har samma dimensioner
d) 2D - 3C
Svar: 2D - 3C = [[3 2]
 [2 3]]
e) DT(transponat av D) + 2D
Svar: DT + 2D [[ 9 12]
 [12  9]]
f) 2CT - 2DT
Svar: [[-4 -4]
 [-4 -4]]
g) AT - B
Svar: AT - B är ej definierad eftersom A efter transponering får 2 kolumner med 3 rader medan B har 3 kolumner med 2 rader
h) AC
Svar: AC ej definierad eftersom A och C  har olika dimensioner
i) CD
Svar: CD = [[11 10]
 [10 11]]
j) CB
Svar: CB ej definierad C och B  har olika dimensioner
k) CI
Svar: CI = [[1 2]
 [2 1]]
l) ABT
Svar: ABT ej definierad eftersom transponatet av B får en annan dimension än A
Uppgift 10.2.2
Definiera matrisen A (på nytt, vi skriver över tidigare A)
Beräkna AAT
Svar: AAT är ej definierad eftersom transponatet av får en annan dimension än A
Uppgift 10.2.3
Definie

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]

print("How do we check if v1 and v2 is a view or copy?")
print("Answer: You can check if it is a view or copy using the 'base' attribut of the ndarray")
if v1.base is None:
    print("v1 is a copy")
else:
    print("v1 is a view")
    
if v2.base is None:
    print("v2 is a copy")
else:
    print("v2 is a view")

print("What happens if we change the last element in v2 to 123? Lets do it")
v2[1] = 123

print("Answer: We can see that when we changed the last element of v2 that is also changed in v1. The reason is simply because v2 is a view and the both point to the same Data buffer.")

print(v1)
print(v2)

[0 1 2 3]
How do we check if v1 and v2 is a view or copy?
Answer: You can check if it is a view or copy using the 'base' attribut of the ndarray
v1 is a copy
v2 is a view
What happens if we change the last element in v2 to 123? Lets do it
Answer: We can see that when we changed the last element of v2 that is also changed in v1. The reason is simply because v2 is a view of v1 and the Data buffer remains the same. In a sense they point to the same object.
[  0   1   2 123]
[  2 123]
