# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)
print(type(A))


2
(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(f"Print B:\n{B}")
print(f"Print C:\n{C}")
print(f"Elementwise subtraction:\n{B-C}")
print(f"Elementwise multiplication:\n{B*C}")
print(f"Matrix multiplication:\n{B@C}")


Print B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Print C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [27]:
D = np.arange(1, 10).reshape(3, 3)
print(D)
print(f"Exponentiate each number elementwise:\n{np.exp(D)}")
print(f"Calc min value in the matrix:\n{np.min(D)}")
print(f"Calc min value in each row:\n{np.min(D, axis=1)}")
print(f"Calc min value in each column:\n{np.min(D, axis=0)}")
print(f"Find index value for the min value in the matrix:\n{np.argmin(D)}")
print(f"Find index value for the min value in each row:\n{np.argmin(D, axis=1)}")
print(f"Calc sum for all elements:\n{np.sum(D)}")
print(f"Calc mean for each column:\n{np.mean(D, axis=0)}")
print(f"Calc median for each column:\n{np.median(D, axis=0)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Exponentiate each number elementwise:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Calc min value in the matrix:
1
Calc min value in each row:
[1 4 7]
Calc min value in each column:
[1 2 3]
Find index value for the min value in the matrix:
0
Find index value for the min value in each row:
[0 0 0]
Calc sum for all elements:
45
Calc mean for each column:
[4. 5. 6.]
Calc median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [28]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
#A[1]
A[1:2]

array([[ 6,  7,  8,  9, 10]])

**Answer:**

In [ ]:
# The answer to the question what it means 
# if you provide fewer indices than axes when slicing is that you
# only get a subset of the axes back. In the first example A[1] you
# will get back the second axes. It is actually implicit slicing 
# it is assumed that you want to 1 axes back. You get the same 
# row back if you explicitly slice A[1:2]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [36]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
A[0][0] = 10 #Just double checking so that we get the values and not the index
# Flatten the multidemension array in order to visit all elements
for i in A.flat:
    print(f"Number:{i}")

Number:10
Number:2
Number:3
Number:4
Number:5
Number:6
Number:7
Number:8
Number:9
Number:10
Number:11
Number:12
Number:13
Number:14
Number:15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [8]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#Answer: We start with a 1D array and reshape it int a 3D Array. 
# In this example we specify that we want 2 outer arrays with 3 arrays in each. 
# The last input value -1 tells NumPy that it can figure out the last dimension by 
# its self. In this instance we have 30 values which should be evenly distributed
# So, 2 x 3 = 6. Since 2 x 3 x 5 = 30 the last input value represents no. of
# columns in each array.

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [24]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [9]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
def add_mult_matrices(m1, m2, operation):
    #Check that m1 and m2 have the correct type, otherwise throw exception or print error message
    if not isinstance(m1, np.ndarray):
        raise TypeError("m1 is not of type numpy.ndarray")
    elif not isinstance(m2, np.ndarray):
        raise TypeError("m2 is not of type numpy.ndarray")
    
    
    
    #Check m1 and m2 so they are compatible to addition and multiplication
    try:
        np.broadcast_shapes(m1.shape, m2.shape)
    except Exception:
        raise ValueError(f"The matrices are not compatible with {operation} operation")
    
    #Check so that operation is either 'add' or 'multiply'
    if operation == 'add':
        return m1 + m2
    else:
        return m1 @ m2
    

arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
arr2 = np.array([1, 2, 4, 8, 16])
print(add_mult_matrices(arr1, arr2, 'add'))


[[ 2  4  7 12 21]
 [ 2  4  7 12 21]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [26]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]
